---
# provision
- hosts: all
  pre_tasks:
    - name: Add www user.
      user:
        name: www
        uid: 1000
        shell: /bin/sh
  roles:
    - role: shomatan.dumb-init
    - role: shomatan.php-fpm
      php_fpm_pool_user: www
      php_fpm_pool_group: www
      #php_fpm_error_log: /proc/self/fd/2
      # TODO: Try this value.
      #php_fpm_error_log: /dev/fd/2
  post_tasks:
    - name: Purge yum cache.
      command: yum clean all

    - name: Get php version.
      command: php --version
      register: result
      changed_when: False
    
    - name: Output php version.
      debug: var=result.stdout